# Generated by Django 2.2.6 on 2019-10-21 09:04

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='<<No author>>', max_length=255)),
                ('middle_name', models.CharField(default='<<No author>>', max_length=255)),
                ('last_name', models.CharField(default='<<No author>>', max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='<<No title>>', max_length=255, verbose_name='Название картинки')),
                ('description', models.CharField(default='<<No description>>', max_length=1024, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=website.models.get_filepath)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='<<No author>>', max_length=255)),
                ('url', models.URLField(default='Simple site')),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='<<No title>>', max_length=255, verbose_name='Заголовок')),
                ('short_description', models.CharField(default='<<No description>>', max_length=1024, verbose_name='Описание')),
                ('published', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('content', models.TextField(default='<<No text>>', verbose_name='Текст статьи')),
                ('author', models.ManyToManyField(to='website.Author')),
                ('illustration', models.ManyToManyField(related_name='newsitems', to='website.ImageItem')),
                ('preview_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsitem', to='website.ImageItem')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Source')),
            ],
        ),
    ]
